/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#006565',
        'primary-container': '#008080',
        'on-primary': '#ffffff',
        'on-primary-container': '#e3fffe',
        'primary-fixed': '#93f2f2',
        'primary-fixed-dim': '#76d6d5',
        'on-primary-fixed': '#002020',
        'on-primary-fixed-variant': '#004f4f',
        'inverse-primary': '#76d6d5',
        secondary: '#006c4f',
        'secondary-container': '#80f9ca',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#007354',
        'secondary-fixed': '#80f9ca',
        'secondary-fixed-dim': '#62dcaf',
        'on-secondary-fixed': '#002116',
        'on-secondary-fixed-variant': '#00513b',
        tertiary: '#775400',
        'tertiary-container': '#976b00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fff8f3',
        'tertiary-fixed': '#ffdea8',
        'tertiary-fixed-dim': '#ffba25',
        'on-tertiary-fixed': '#271900',
        'on-tertiary-fixed-variant': '#5e4200',
        surface: '#f7fafa',
        'surface-dim': '#d7dbdb',
        'surface-bright': '#f7fafa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f4',
        'surface-container': '#ebeeee',
        'surface-container-high': '#e6e9e9',
        'surface-container-highest': '#e0e3e3',
        'on-surface': '#181c1d',
        'on-surface-variant': '#3e4949',
        'surface-variant': '#e0e3e3',
        'surface-tint': '#006a6a',
        'inverse-surface': '#2d3131',
        'inverse-on-surface': '#eef1f1',
        outline: '#6e7979',
        'outline-variant': '#bdc9c8',
        background: '#f7fafa',
        'on-background': '#181c1d',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['WorkSans', 'System'],
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'margin-main': '24px',
        'gutter-grid': '16px',
        'touch-min': '48px',
      },
    },
  },
  plugins: [],
};
